#include <iostream>
#include <iomanip>
#include <fstream>
#include <sstream>
#include <cmath>
#include <vector>
#include <string>
#include <limits>
#include <memory>

using namespace std;

const std::string filenameA = "partial_capsid.xyz";
const std::string filenameB = "P2.xyz";

const double pi = 3.14159265358979;
const int NTAB = 32;
const int NDIV = 1 + (2147483563 - 1) / NTAB;
const double EPS = 1.2e-21;
const double RNMX = 1.0 - EPS;
int idum = -873; 

const double sphereCenter[3] = {73.88699, 0.0, 0.0}; // Center of the sphere
const double sphereRadius = 122.0;                  // Radius of the sphere

#define MBIG 1000000000
#define MSEED 161803398
#define MZ 0
#define FAC (1.0/MBIG)

struct Atom {
    char type;
    double coords[3];
};

// Function to read data from a file into a vector of atoms
void readData(const string& filename, vector<Atom>& atoms, int& numatoms) {
    ifstream inFile(filename); // Open the file for reading
    string line;

    // Check if the file opened successfully
    if (!inFile.is_open()) {
        cerr << "Error: Could not open file " << filename << endl;
        return;
    }

    // Check if the first line contains the number of atoms
    if (getline(inFile, line)) {
        istringstream iss(line);
        iss >> numatoms;
        cout << "Number of atoms: " << numatoms << endl;
        atoms.resize(numatoms); // Allocate exact needed space
    } else {
        cerr << "Error: Could not read the number of atoms from the file." << endl;
        inFile.close();
        return;
    }

    // Skip the second line (e.g., "generated by VMD")
    if (!getline(inFile, line)) {
        cerr << "Error: File ended unexpectedly while skipping the second line." << endl;
        inFile.close();
        return;
    }

    // Loop through each atom and read its details from subsequent lines
    for (int i = 0; i < numatoms; ++i) {
        if (getline(inFile, line)) {
            istringstream iss(line);
            iss >> atoms[i].type >> atoms[i].coords[0] >> atoms[i].coords[1] >> atoms[i].coords[2];
        } else {
            cerr << "Error: File ended unexpectedly while reading atom data." << endl;
            break;
        }
    }

    inFile.close(); // Close the file after reading
}

// Function to store initial coordinates to an output file
void InitialCoordinates(const string& filename, const vector<Atom>& atoms, int numatoms) {
    ofstream outFile(filename);  // Open the output file for writing
    outFile << numatoms << "\nThis is an xyz file\n";  // Write number of atoms and a header line

    // Loop through each atom and write its details to the file
    for (int i = 0; i < numatoms; ++i) {
        // Write atom type and coordinates to the file
        outFile << atoms[i].type << "      " << atoms[i].coords[0] << "     " 
                << atoms[i].coords[1] << "        " << atoms[i].coords[2] << "\n";
    }

    outFile.close();  // Close the output file
} 

// Function to generate random numbers using the ran3 algorithm
float ran3(int *idum) {
    // Define static variables to retain state between function calls
    static int inext, inextp;
    static long ma[56];
    static int iff=0;
    long mj, mk;
    int i, ii, k;

    // Initialize the random number generator if required
    if (*idum < 0 || iff == 0) {
        iff=1;
        mj=MSEED-(*idum < 0 ? -*idum : *idum);
        mj %= MBIG;
        ma[55]=mj;
        mk=1;
        // Initialize the state vector
        for (i=1; i<54; i++) {
            ii=(21*i) % 55;
            ma[ii]=mk;
            mk=mj-mk;
            if (mk < MZ) mk += MBIG;
            mj=ma[ii];
        }
        // Shuffle the state vector
        for (k=1; k<=4; k++)
            for (i=1; i<=55; i++) {
                ma[i] -= ma[1+(i+30) % 55];
                if (ma[i] < MZ) ma[i] += MBIG;
            }
        // Reset pointers and seed
        inext=0;
        inextp=31;
        *idum=1;
    }

    // Update pointers for the next random number
    if (++inext == 56) inext=1;
    if (++inextp == 56) inextp=1;
    mj=ma[inext]-ma[inextp];
    if (mj < MZ) mj += MBIG;
    ma[inext]=mj;

    // Return the random number scaled by a factor
    return mj*FAC;
}

void MoveRandomRotateXYZMoveBack(const string& filename, const string& outputFilename, vector<Atom>& atoms, int numatoms) {
    ifstream inFile(filename); // Open input file
    string junk;

    // Read the original number of atoms from the file
    int originalNumAtoms;
    inFile >> originalNumAtoms;
    getline(inFile, junk); // Consume rest of the line

    // Calculate the translation values to move atoms to origin
    double movex = -atoms[0].coords[0];
    double movey = -atoms[0].coords[1];
    double movez = -atoms[0].coords[2];

    // Translate all atoms to the origin
    for (int i = 0; i < numatoms; ++i) {
        atoms[i].coords[0] += movex;
        atoms[i].coords[1] += movey;
        atoms[i].coords[2] += movez;
    }

    // Generate random angles for rotation
    double alpha = ran3(&idum) * 2.0 * pi;
    double beta = ran3(&idum) * 2.0 * pi;
    double gamma = ran3(&idum) * 2.0 * pi;
    cout << "Rotation angles: " << alpha << "  " << beta << "  " << gamma << endl;

    // Calculate the rotation matrix
    double matrix[3][3] = {
        {cos(beta) * cos(gamma), cos(beta) * sin(gamma), -sin(beta)},
        {sin(alpha) * sin(beta) * cos(gamma) - cos(alpha) * sin(gamma),
         sin(alpha) * sin(beta) * sin(gamma) + cos(alpha) * cos(gamma),
         sin(alpha) * cos(beta)},
        {cos(alpha) * sin(beta) * cos(gamma) + sin(alpha) * sin(gamma),
         cos(alpha) * sin(beta) * sin(gamma) - sin(alpha) * cos(gamma),
         cos(alpha) * cos(beta)}
    };

    // Apply rotation to all atoms
    for (int i = 0; i < numatoms; ++i) {
        double x = atoms[i].coords[0];
        double y = atoms[i].coords[1];
        double z = atoms[i].coords[2];

        atoms[i].coords[0] = matrix[0][0] * x + matrix[0][1] * y + matrix[0][2] * z;
        atoms[i].coords[1] = matrix[1][0] * x + matrix[1][1] * y + matrix[1][2] * z;
        atoms[i].coords[2] = matrix[2][0] * x + matrix[2][1] * y + matrix[2][2] * z;
    }

    // Write rotation matrix to a file
    ofstream matrixFile("rotation_matrix.txt");
    if (matrixFile.is_open()) {
        for (int i = 0; i < 4; ++i) {
            for (int j = 0; j < 4; ++j) {
                if (i < 3 && j < 3) {
                    matrixFile << matrix[i][j] << " ";
                } else if (i == 3 && j == 3) {
                    matrixFile << "1";
                } else {
                    matrixFile << "0";
                }
                if (j < 3) {
                    matrixFile << " ";
                }
            }
            matrixFile << endl;
        }
        matrixFile.close();
    }

    // Translate all atoms back to their original positions
    for (int i = 0; i < numatoms; ++i) {
        atoms[i].coords[0] -= movex;
        atoms[i].coords[1] -= movey;
        atoms[i].coords[2] -= movez;
    }

    // Write updated atom positions to the output file
    ofstream outFile(outputFilename);
    outFile << numatoms << "\nThis is an xyz file\n";
    for (int i = 0; i < numatoms; ++i) {
        outFile << atoms[i].type << "   " << atoms[i].coords[0] << "    " 
                << atoms[i].coords[1] << "    " << atoms[i].coords[2] << "\n";
    }

    // Close input and output files
    inFile.close();
    outFile.close();
}

// Structure to store configuration data
struct Configuration {
    vector<Atom> atoms;
    int numAtoms;
    int failureCount;
    double minDistance;
    
    Configuration() : numAtoms(0), failureCount(INT_MAX), minDistance(0.0) {}
};

double calculateMinimumDistance(const vector<Atom>& atomsA, const vector<Atom>& atomsB) {
    double mindist = numeric_limits<double>::infinity();

    // Iterate over atoms in set A (capsid)
    for (const auto& atomA : atomsA) {
        // Iterate over atoms in set B (protein)
        for (const auto& atomB : atomsB) {
            // Calculate squared differences in coordinates
            double dx = atomB.coords[0] - atomA.coords[0];
            double dy = atomB.coords[1] - atomA.coords[1];
            double dz = atomB.coords[2] - atomA.coords[2];
            
            // Calculate distance between atoms
            double dist = sqrt(dx*dx + dy*dy + dz*dz);

            // Update minimum distance if the calculated distance is smaller
            if (dist < mindist) {
                mindist = dist;
            }
        }
    }

    return mindist; // Return the minimum distance
}

// Function to count how many atom pairs fail the distance check
int countDistanceFailures(const vector<Atom>& atomsA, const vector<Atom>& atomsB, double threshold) {
    int failureCount = 0;

    // Iterate over atoms in set A (capsid)
    for (const auto& atomA : atomsA) {
        // Iterate over atoms in set B (protein)
        for (const auto& atomB : atomsB) {
            // Calculate distance between atoms
            double dx = atomB.coords[0] - atomA.coords[0];
            double dy = atomB.coords[1] - atomA.coords[1];
            double dz = atomB.coords[2] - atomA.coords[2];
            double dist = sqrt(dx*dx + dy*dy + dz*dz);

            // Count failures (distances below threshold)
            if (dist < threshold) {
                failureCount++;
            }
        }
    }

    return failureCount;
}

// Function to check if all atoms in a set are OUTSIDE the sphere
bool checkAtomsOutsideSphere(const vector<Atom>& atoms, const double center[3], double radius) {
    for (const auto& atom : atoms) {
        double dx = atom.coords[0] - center[0];
        double dy = atom.coords[1] - center[1];
        double dz = atom.coords[2] - center[2];
        double distanceSquared = dx * dx + dy * dy + dz * dz;

        if (distanceSquared <= radius * radius) {
            return false; // At least one atom is inside or on the sphere
        }
    }
    return true; // All atoms are outside the sphere
}


// Function to calculate rotation matrix from original to transformed coordinates
void calculateAndWriteRotationMatrix(const string& originalFile, const string& transformedFile, const string& outputFile) {
    vector<Atom> originalAtoms, transformedAtoms;
    int numOriginal, numTransformed;
    
    // Read both coordinate files
    readData(originalFile, originalAtoms, numOriginal);
    readData(transformedFile, transformedAtoms, numTransformed);
    
    if (numOriginal != numTransformed) {
        cout << "Error: Atom count mismatch between files" << endl;
        return;
    }
    
    // Calculate centroids
    double centroidOrig[3] = {0.0, 0.0, 0.0};
    double centroidTrans[3] = {0.0, 0.0, 0.0};
    
    for (int i = 0; i < numOriginal; i++) {
        for (int j = 0; j < 3; j++) {
            centroidOrig[j] += originalAtoms[i].coords[j];
            centroidTrans[j] += transformedAtoms[i].coords[j];
        }
    }
    
    for (int j = 0; j < 3; j++) {
        centroidOrig[j] /= numOriginal;
        centroidTrans[j] /= numOriginal;
    }
    
    // Center the coordinates
    vector<vector<double>> origCentered(numOriginal, vector<double>(3));
    vector<vector<double>> transCentered(numOriginal, vector<double>(3));
    
    for (int i = 0; i < numOriginal; i++) {
        for (int j = 0; j < 3; j++) {
            origCentered[i][j] = originalAtoms[i].coords[j] - centroidOrig[j];
            transCentered[i][j] = transformedAtoms[i].coords[j] - centroidTrans[j];
        }
    }
    
    // Calculate cross-covariance matrix H = sum(orig * trans^T)
    double H[3][3] = {{0.0}};
    for (int i = 0; i < numOriginal; i++) {
        for (int row = 0; row < 3; row++) {
            for (int col = 0; col < 3; col++) {
                H[row][col] += origCentered[i][row] * transCentered[i][col];
            }
        }
    }
    
    // For simplicity, use Kabsch algorithm approximation
    // Calculate R using SVD approximation method
    // This is a simplified version - for production code, you'd want proper SVD
    
    // Calculate rotation matrix using cross product method for approximation
    double R[3][3];
    
    // Method: Use the first three non-collinear points to establish coordinate systems
    // Find two vectors in original coordinates
    int idx1 = 0, idx2 = 1, idx3 = 2;
    
    // Ensure we have non-collinear points
    while (idx3 < numOriginal) {
        double v1[3], v2[3];
        for (int i = 0; i < 3; i++) {
            v1[i] = origCentered[idx2][i] - origCentered[idx1][i];
            v2[i] = origCentered[idx3][i] - origCentered[idx1][i];
        }
        
        // Check if vectors are not collinear (cross product magnitude > threshold)
        double cross[3];
        cross[0] = v1[1]*v2[2] - v1[2]*v2[1];
        cross[1] = v1[2]*v2[0] - v1[0]*v2[2];
        cross[2] = v1[0]*v2[1] - v1[1]*v2[0];
        
        double crossMag = sqrt(cross[0]*cross[0] + cross[1]*cross[1] + cross[2]*cross[2]);
        if (crossMag > 1e-6) break;
        idx3++;
    }
    
    // Build orthonormal basis for original coordinates
    double origBasis[3][3];
    // First vector
    for (int i = 0; i < 3; i++) {
        origBasis[0][i] = origCentered[idx2][i] - origCentered[idx1][i];
    }
    double norm = sqrt(origBasis[0][0]*origBasis[0][0] + origBasis[0][1]*origBasis[0][1] + origBasis[0][2]*origBasis[0][2]);
    for (int i = 0; i < 3; i++) origBasis[0][i] /= norm;
    
    // Second vector (Gram-Schmidt)
    for (int i = 0; i < 3; i++) {
        origBasis[1][i] = origCentered[idx3][i] - origCentered[idx1][i];
    }
    double dot = origBasis[0][0]*origBasis[1][0] + origBasis[0][1]*origBasis[1][1] + origBasis[0][2]*origBasis[1][2];
    for (int i = 0; i < 3; i++) origBasis[1][i] -= dot * origBasis[0][i];
    norm = sqrt(origBasis[1][0]*origBasis[1][0] + origBasis[1][1]*origBasis[1][1] + origBasis[1][2]*origBasis[1][2]);
    for (int i = 0; i < 3; i++) origBasis[1][i] /= norm;
    
    // Third vector (cross product)
    origBasis[2][0] = origBasis[0][1]*origBasis[1][2] - origBasis[0][2]*origBasis[1][1];
    origBasis[2][1] = origBasis[0][2]*origBasis[1][0] - origBasis[0][0]*origBasis[1][2];
    origBasis[2][2] = origBasis[0][0]*origBasis[1][1] - origBasis[0][1]*origBasis[1][0];
    
    // Build orthonormal basis for transformed coordinates
    double transBasis[3][3];
    // First vector
    for (int i = 0; i < 3; i++) {
        transBasis[0][i] = transCentered[idx2][i] - transCentered[idx1][i];
    }
    norm = sqrt(transBasis[0][0]*transBasis[0][0] + transBasis[0][1]*transBasis[0][1] + transBasis[0][2]*transBasis[0][2]);
    for (int i = 0; i < 3; i++) transBasis[0][i] /= norm;
    
    // Second vector (Gram-Schmidt)
    for (int i = 0; i < 3; i++) {
        transBasis[1][i] = transCentered[idx3][i] - transCentered[idx1][i];
    }
    dot = transBasis[0][0]*transBasis[1][0] + transBasis[0][1]*transBasis[1][1] + transBasis[0][2]*transBasis[1][2];
    for (int i = 0; i < 3; i++) transBasis[1][i] -= dot * transBasis[0][i];
    norm = sqrt(transBasis[1][0]*transBasis[1][0] + transBasis[1][1]*transBasis[1][1] + transBasis[1][2]*transBasis[1][2]);
    for (int i = 0; i < 3; i++) transBasis[1][i] /= norm;
    
    // Third vector (cross product)
    transBasis[2][0] = transBasis[0][1]*transBasis[1][2] - transBasis[0][2]*transBasis[1][1];
    transBasis[2][1] = transBasis[0][2]*transBasis[1][0] - transBasis[0][0]*transBasis[1][2];
    transBasis[2][2] = transBasis[0][0]*transBasis[1][1] - transBasis[0][1]*transBasis[1][0];
    
    // Calculate rotation matrix R = transBasis * origBasis^T
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            R[i][j] = 0.0;
            for (int k = 0; k < 3; k++) {
                R[i][j] += transBasis[i][k] * origBasis[j][k];
            }
        }
    }
    
    // Write rotation matrix to file
    ofstream matrixFile(outputFile);
    if (!matrixFile.is_open()) {
        cout << "Error: Could not open " << outputFile << " for writing" << endl;
        return;
    }
    
    matrixFile << "# Rotation matrix from " << originalFile << " to " << transformedFile << endl;
    matrixFile << "# Format: 3x3 rotation matrix (row-major order)" << endl;
    matrixFile << "# Apply as: new_coord = R * old_coord" << endl;
    matrixFile << fixed << setprecision(8);
    
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            matrixFile << setw(15) << R[i][j];
            if (j < 2) matrixFile << "  ";
        }
        matrixFile << endl;
    }
    
    matrixFile.close();
    cout << "Rotation matrix written to " << outputFile << endl;
    
    // Optional: Print matrix to console for verification
    cout << "Rotation matrix:" << endl;
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            cout << setw(10) << setprecision(4) << R[i][j] << " ";
        }
        cout << endl;
    }
}

int main () {
    const double mindist_threshold = 0.50; // Threshold for minimum distance
    const int maxDistanceChecks = 100; // Maximum number of distance checks
    const int topConfigsToSave = 5; // Number of best configurations to save
    bool sphereRejectSaved = false;
    int failureImageCount = 0;
    const int failureImagesToSave = 4; // How many failure examples you want
    
    vector<Atom> atomsA;  // Capsid atoms
    vector<Atom> atomsB;  // Protein atoms
    vector<Atom> initialAtomsB;  // Initial protein coordinates
    int numatomsA, numatomsB;
    int attempts = 0;
    int distanceChecks = 0;
    const int maxAttempts = 1000000; // Prevent infinite loops in sphere checking
    
    // Array to store the best configurations
    vector<Configuration> bestConfigs(topConfigsToSave);
        
    // Read data from files into vectors of atoms
    readData(filenameA, atomsA, numatomsA);
    readData(filenameB, atomsB, numatomsB);  

    // Copy atomsB to initialAtomsB
    initialAtomsB = atomsB;
    
    // Write initial coordinates to a file
    InitialCoordinates("initial_coordinates.xyz", initialAtomsB, numatomsB);

    bool perfectSolutionFound = false;
    
    cout << "Starting placement attempts..." << endl;
    cout << "Target: minimum distance >= " << mindist_threshold << " Angstroms" << endl;
    cout << "Target: all atoms outside sphere (center: " << sphereCenter[0] << ", " 
         << sphereCenter[1] << ", " << sphereCenter[2] << ", radius: " << sphereRadius << ")" << endl;
    cout << "Will perform maximum " << maxDistanceChecks << " distance checks" << endl;
    cout << "Will save top " << topConfigsToSave << " configurations" << endl;

    while (distanceChecks < maxDistanceChecks && !perfectSolutionFound && attempts < maxAttempts) {
        attempts++;
        
        // Apply random rotation
        MoveRandomRotateXYZMoveBack(filenameB, "temp_coordinates.xyz", atomsB, numatomsB);

        // FIRST: Check if protein is outside the sphere (fast check)
        bool isOutsideSphere = checkAtomsOutsideSphere(atomsB, sphereCenter, sphereRadius);
        
        if (isOutsideSphere) {
            // SECOND: Perform distance check (expensive operation)
            distanceChecks++;
            
            double mindist = calculateMinimumDistance(atomsA, atomsB);
            int failureCount = countDistanceFailures(atomsA, atomsB, mindist_threshold);
            
            cout << "Distance check " << distanceChecks << "/" << maxDistanceChecks 
                 << " (attempt " << attempts << "): ";
            cout << "Min distance = " << mindist << ", Failures = " << failureCount;
            
            if (failureCount == 0) {
                cout << " -> PERFECT SOLUTION FOUND!" << endl;
                perfectSolutionFound = true;
                
                // Save the perfect solution
                bestConfigs[0].atoms = atomsB;
                bestConfigs[0].numAtoms = numatomsB;
                bestConfigs[0].failureCount = 0;
                bestConfigs[0].minDistance = mindist;
                break;
            } else {
                cout << endl;
                
                //Save failure visualization examples
                if (failureImageCount < failureImagesToSave) {
                    string filename = "image_failure_" + to_string(failureImageCount + 1) + ".xyz";
                    ofstream failFile(filename);
                    failFile << numatomsB << "\nFailure example " << (failureImageCount + 1)
                             << " - Failures: " << failureCount << "\n";
                    for (int i = 0; i < numatomsB; ++i) {
                        failFile << atomsB[i].type << "   "
                                << atomsB[i].coords[0] << "    "
                                << atomsB[i].coords[1] << "    "
                                << atomsB[i].coords[2] << "\n";
                    }
                    failFile.close();
                    failureImageCount++;
                    cout << "  -> Saved failure visualization example "
                         << failureImageCount << "/" << failureImagesToSave << endl;
                }
                // Check if this configuration should be saved in top 5
                // Find the worst configuration in our saved list
                int worstIndex = 0;
                for (int i = 1; i < topConfigsToSave; ++i) {
                    if (bestConfigs[i].failureCount > bestConfigs[worstIndex].failureCount) {
                        worstIndex = i;
                    }
                }
                
                // If current configuration is better than the worst saved one
                if (failureCount < bestConfigs[worstIndex].failureCount) {
                    // Save this configuration
                    bestConfigs[worstIndex].atoms = atomsB;
                    bestConfigs[worstIndex].numAtoms = numatomsB;
                    bestConfigs[worstIndex].failureCount = failureCount;
                    bestConfigs[worstIndex].minDistance = mindist;
                    
                    cout << "  -> New top-5 configuration! (replaced config with " 
                         << bestConfigs[worstIndex].failureCount << " failures)" << endl;
                }
            }
        } else {
            // Save one example of a sphere-rejected configuration
            if (!sphereRejectSaved) {
                ofstream rejectFile("image_sphere_reject.xyz");
                rejectFile << numatomsB << "\nSphere rejection example\n";
                for (int i = 0; i < numatomsB; ++i) {
                    rejectFile << atomsB[i].type << "   "
                              << atomsB[i].coords[0] << "    "
                              << atomsB[i].coords[1] << "    "
                              << atomsB[i].coords[2] << "\n";
                }
                rejectFile.close();
                sphereRejectSaved = true;
                cout << "Saved sphere rejection example for visualization." << endl;
            }
            // Print progress for sphere checks occasionally
            if (attempts % 10000 == 0) {
                cout << "Attempt " << attempts << ": Inside sphere, skipping distance check" << endl;
            }
        }

        // Reset to initial coordinates for next attempt
        atomsB = initialAtomsB;
    }

    // Print final results
    cout << "\n=== FINAL RESULTS ===" << endl;
    cout << "Total attempts: " << attempts << endl;
    cout << "Distance checks performed: " << distanceChecks << endl;
    
    if (perfectSolutionFound) {
        cout << "PERFECT SOLUTION FOUND with 0 distance failures!" << endl;
        
        // Save the perfect solution
        ofstream perfectFile("perfect_solution.xyz");
        perfectFile << bestConfigs[0].numAtoms << "\nPerfect solution - 0 failures\n";
        for (int i = 0; i < bestConfigs[0].numAtoms; ++i) {
            perfectFile << bestConfigs[0].atoms[i].type << "   " 
                       << bestConfigs[0].atoms[i].coords[0] << "    " 
                       << bestConfigs[0].atoms[i].coords[1] << "    " 
                       << bestConfigs[0].atoms[i].coords[2] << "\n";
        }
        perfectFile.close();
    } else {
        cout << "No perfect solution found. Saving best configurations:" << endl;
        
        // Sort configurations by failure count (ascending)
        for (int i = 0; i < topConfigsToSave - 1; ++i) {
            for (int j = i + 1; j < topConfigsToSave; ++j) {
                if (bestConfigs[j].failureCount < bestConfigs[i].failureCount) {
                    swap(bestConfigs[i], bestConfigs[j]);
                }
            }
        }
        
        // Save the best configurations
        for (int config = 0; config < topConfigsToSave; ++config) {
            if (bestConfigs[config].failureCount < INT_MAX) {
                string filename = "best_config_" + to_string(config + 1) + ".xyz";
                ofstream configFile(filename);
                configFile << bestConfigs[config].numAtoms 
                          << "\nConfiguration " << (config + 1) 
                          << " - Failures: " << bestConfigs[config].failureCount
                          << " - Min distance: " << bestConfigs[config].minDistance << "\n";
                
                for (int i = 0; i < bestConfigs[config].numAtoms; ++i) {
                    configFile << bestConfigs[config].atoms[i].type << "   " 
                              << bestConfigs[config].atoms[i].coords[0] << "    " 
                              << bestConfigs[config].atoms[i].coords[1] << "    " 
                              << bestConfigs[config].atoms[i].coords[2] << "\n";
                }
                configFile.close();
                
                cout << "Config " << (config + 1) << ": " << bestConfigs[config].failureCount 
                     << " failures, min distance = " << bestConfigs[config].minDistance 
                     << " -> saved as " << filename << endl;
            }
        }
     if (bestConfigs[0].failureCount < INT_MAX) {
            cout << "\nCalculating rotation matrix from original to best configuration..." << endl;
            calculateAndWriteRotationMatrix("P2.xyz", "best_config_1.xyz", "rotation_matrix.txt");
        }
    }

    return 0;
}